CREATE
  TABLE HUB_ORDER
  (
    DV_ORDER_ID BIGINT NOT NULL ,
    BK_ORDERCODE  VARCHAR (255) NOT NULL ,
    LOAD_DTS      DATETIME NOT NULL ,
    RECORD_SOURCE VARCHAR (10) NOT NULL ,
    ETL_RUN_ID BIGINT NOT NULL
  )
  ON "default"
GO
