CREATE
  TABLE HUB_PRODUCT_TYPE
  (
    DV_PRODUCT_TYPE_ID BIGINT NOT NULL ,
    BK_PRODUCT_TYPE VARCHAR (255) NOT NULL ,
    LOAD_DTS        DATETIME NOT NULL ,
    RECORD_SOURCE   VARCHAR (10) NOT NULL ,
    ETL_RUN_ID BIGINT NOT NULL
  )
  ON "default"
GO
