CREATE
  TABLE HUB_CUSTOMER
  (
    DV_CUSTOMER_ID BIGINT NOT NULL ,
    BK1_EMAIL      VARCHAR (255) NOT NULL ,
    BK2_CHANNEL_ID INTEGER NOT NULL ,
    LOAD_DTS       DATETIME NOT NULL ,
    RECORD_SOURCE  VARCHAR (10) NOT NULL ,
    ETL_RUN_ID BIGINT NOT NULL
  )
  ON "default"
GO
