CREATE
  TABLE HUB_PRODUCT
  (
    DV_PRODUCT_ID BIGINT NOT NULL ,
    BK_PRODUCT    VARCHAR (255) NOT NULL ,
    LOAD_DTS      DATETIME NOT NULL ,
    RECORD_SOURCE VARCHAR (10) NOT NULL ,
    ETL_RUN_ID BIGINT NOT NULL
  )
  ON "default"
GO
