CREATE
  TABLE LNK_ORDERLINE
  (
    LOAD_DTS      DATETIME NOT NULL ,
    RECORD_SOURCE VARCHAR (10) NOT NULL ,
    ETL_RUN_ID BIGINT NOT NULL ,
    DV_ORDER_ID BIGINT NOT NULL ,
    DV_PRODUCT_ID BIGINT NOT NULL ,
    DV_ORDERLINE_ID INTEGER NOT NULL
  )
  ON "default"
GO
