CREATE
  TABLE LNK_PRODUCT_PRODUCTTYPE
  (
    DV_PRODUCT_PRODUCTTYPE_ID INTEGER NOT NULL ,
    LOAD_DTS                  DATETIME NOT NULL ,
    RECORD_SOURCE             VARCHAR (10) NOT NULL ,
    ETL_RUN_ID BIGINT NOT NULL ,
    DV_PRODUCT_ID BIGINT NOT NULL ,
    DV_PRODUCT_TYPE_ID BIGINT NOT NULL
  )
  ON "default"
GO
