ALTER TABLE LNK_PRODUCT_PRODUCTTYPE ADD CONSTRAINT LNK_PRODUCT_PRODUCTTYPE_PK
PRIMARY KEY CLUSTERED (DV_PRODUCT_PRODUCTTYPE_ID)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
GO