CREATE
  TABLE LNK_CUSTOMER_ORDER
  (
    DV_CUSTOMER_ORDER_ID BIGINT NOT NULL ,
    LOAD_DTS      DATETIME NOT NULL ,
    RECORD_SOURCE VARCHAR (10) NOT NULL ,
    ETL_RUN_ID BIGINT NOT NULL ,
    DV_CUSTOMER_ID BIGINT NOT NULL ,
    DV_ORDER_ID BIGINT NOT NULL
  )
  ON "default"
GO
