CREATE
  TABLE SAT_ORDER_1
  (
    ORDERDATE  DATETIME NOT NULL ,
    VALID_FROM DATETIME NOT NULL ,
    VALID_TO   DATETIME ,
    IS_CURRENT BIT ,
    LOAD_DTS      DATETIME NOT NULL ,
    RECORD_SOURCE VARCHAR (10) NOT NULL ,
    ETL_RUN_ID BIGINT NOT NULL ,
    DV_ORDER_ID BIGINT NOT NULL
  )
  ON "default"
GO
